---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(glue)
library(here)
library(readr)
library(stringr)
library(tidyr)
```

```{r}
demo_df <-
  read_csv(here("data/redcap_export_SPINS_2020-05-06.csv")) %>%
  mutate(group = case_when(grepl("arm_1", redcap_event_name) ~ "Control",
                           grepl("arm_2", redcap_event_name) ~ "Case")) %>%
  filter(redcap_event_name != "cl_arm_3") %>%
  separate(record_id, c("study", "site", "id")) %>%
  mutate(subject_id = glue("sub-{site}{id}")) %>%
  select(subject_id, group)
```

```{r}
task_df <-
  read_csv(here("data/compiled_ea_scores.csv")) %>%
  separate(sub_id, c("study", "site", "id", "session", "visit")) %>%
  mutate(subject_id = glue("sub-{site}{id}"),
         session_label = glue("ses-{session}"),
         run_extract = str_extract(orig_file, "part([1-3]{1}).log") %>%
           gsub("part", "", .) %>% gsub(".log", "", .),
         run = glue("run-{run_extract}")) %>%
  select(subject_id, session_label, run, stim_file, score)
```

```{r}
median_score <-
  task_df %>%
  select(score) %>%
  unlist() %>%
  median(., na.rm = TRUE)
```

```{r}
mriqc_df <-
  read_tsv(here("data/group_bold.tsv")) %>%
  separate(bids_name, c("subject_id", "session_label", "task_name", "run"), sep = "_", extra = "merge") %>%
  mutate(run = gsub("bold|_bold", "", run)) %>%
  filter(task_name == "task-emp") %>%
  select(subject_id:run, fd_mean:fd_perc)
```

```{r}
filtered_task_df <-
  mriqc_df %>%
  left_join(demo_df) %>%
  left_join(task_df) %>%
  filter(grepl("CMH", subject_id)) %>%
  filter(fd_mean < 0.2 & score > median_score)
```

```{r}
subject_list <-
  filtered_task_df %>%
  filter(subject_id %in% subject_list) %>%
  select(subject_id, group) %>%
  unique() %>%
  group_by(group) %>%
  sample_n(5) %>%
  ungroup() %>%
  select(subject_id) %>%
  arrange(subject_id)

subject_list %>%
  write_tsv(here("data/subject_list.txt"), col_names = FALSE)
```
